/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	dividerv1 "github.com/kubeedge/kubeedge/cloud/cmd/inter_cluster_gateway/pkg/apis/divider/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDividers implements DividerInterface
type FakeDividers struct {
	Fake *FakeMizarV1
	ns   string
}

var dividersResource = schema.GroupVersionResource{Group: "mizar.com", Version: "v1", Resource: "dividers"}

var dividersKind = schema.GroupVersionKind{Group: "mizar.com", Version: "v1", Kind: "Divider"}

// Get takes name of the divider, and returns the corresponding divider object, and an error if there is any.
func (c *FakeDividers) Get(ctx context.Context, name string, options v1.GetOptions) (result *dividerv1.Divider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dividersResource, c.ns, name), &dividerv1.Divider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dividerv1.Divider), err
}

// List takes label and field selectors, and returns the list of Dividers that match those selectors.
func (c *FakeDividers) List(ctx context.Context, opts v1.ListOptions) (result *dividerv1.DividerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dividersResource, dividersKind, c.ns, opts), &dividerv1.DividerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &dividerv1.DividerList{ListMeta: obj.(*dividerv1.DividerList).ListMeta}
	for _, item := range obj.(*dividerv1.DividerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dividers.
func (c *FakeDividers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dividersResource, c.ns, opts))

}

// Create takes the representation of a divider and creates it.  Returns the server's representation of the divider, and an error, if there is any.
func (c *FakeDividers) Create(ctx context.Context, divider *dividerv1.Divider, opts v1.CreateOptions) (result *dividerv1.Divider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dividersResource, c.ns, divider), &dividerv1.Divider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dividerv1.Divider), err
}

// Update takes the representation of a divider and updates it. Returns the server's representation of the divider, and an error, if there is any.
func (c *FakeDividers) Update(ctx context.Context, divider *dividerv1.Divider, opts v1.UpdateOptions) (result *dividerv1.Divider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dividersResource, c.ns, divider), &dividerv1.Divider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dividerv1.Divider), err
}

// Delete takes name of the divider and deletes it. Returns an error if one occurs.
func (c *FakeDividers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dividersResource, c.ns, name), &dividerv1.Divider{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDividers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dividersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &dividerv1.DividerList{})
	return err
}

// Patch applies the patch and returns the patched divider.
func (c *FakeDividers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dividerv1.Divider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dividersResource, c.ns, name, pt, data, subresources...), &dividerv1.Divider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dividerv1.Divider), err
}
