/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	subnetv1 "github.com/kubeedge/kubeedge/cloud/cmd/inter_cluster_gateway/pkg/apis/subnet/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubnets implements SubnetInterface
type FakeSubnets struct {
	Fake *FakeMizarV1
	ns   string
}

var subnetsResource = schema.GroupVersionResource{Group: "mizar.com", Version: "v1", Resource: "subnets"}

var subnetsKind = schema.GroupVersionKind{Group: "mizar.com", Version: "v1", Kind: "Subnet"}

// Get takes name of the subnet, and returns the corresponding subnet object, and an error if there is any.
func (c *FakeSubnets) Get(ctx context.Context, name string, options v1.GetOptions) (result *subnetv1.Subnet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subnetsResource, c.ns, name), &subnetv1.Subnet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*subnetv1.Subnet), err
}

// List takes label and field selectors, and returns the list of Subnets that match those selectors.
func (c *FakeSubnets) List(ctx context.Context, opts v1.ListOptions) (result *subnetv1.SubnetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subnetsResource, subnetsKind, c.ns, opts), &subnetv1.SubnetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &subnetv1.SubnetList{ListMeta: obj.(*subnetv1.SubnetList).ListMeta}
	for _, item := range obj.(*subnetv1.SubnetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subnets.
func (c *FakeSubnets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subnetsResource, c.ns, opts))

}

// Create takes the representation of a subnet and creates it.  Returns the server's representation of the subnet, and an error, if there is any.
func (c *FakeSubnets) Create(ctx context.Context, subnet *subnetv1.Subnet, opts v1.CreateOptions) (result *subnetv1.Subnet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subnetsResource, c.ns, subnet), &subnetv1.Subnet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*subnetv1.Subnet), err
}

// Update takes the representation of a subnet and updates it. Returns the server's representation of the subnet, and an error, if there is any.
func (c *FakeSubnets) Update(ctx context.Context, subnet *subnetv1.Subnet, opts v1.UpdateOptions) (result *subnetv1.Subnet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subnetsResource, c.ns, subnet), &subnetv1.Subnet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*subnetv1.Subnet), err
}

// Delete takes name of the subnet and deletes it. Returns an error if one occurs.
func (c *FakeSubnets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(subnetsResource, c.ns, name), &subnetv1.Subnet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubnets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subnetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &subnetv1.SubnetList{})
	return err
}

// Patch applies the patch and returns the patched subnet.
func (c *FakeSubnets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *subnetv1.Subnet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subnetsResource, c.ns, name, pt, data, subresources...), &subnetv1.Subnet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*subnetv1.Subnet), err
}
