// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mizar.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	mizar.proto

It has these top-level messages:
	CreateVpcGatewayRequest
	CreateSubnetRequest
	DeleteVpcGatewayRequest
	DeleteSubnetRequest
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_CodeType int32

const (
	Response_Error Response_CodeType = 0
	Response_OK    Response_CodeType = 1
)

var Response_CodeType_name = map[int32]string{
	0: "Error",
	1: "OK",
}
var Response_CodeType_value = map[string]int32{
	"Error": 0,
	"OK":    1,
}

func (x Response_CodeType) String() string {
	return proto1.EnumName(Response_CodeType_name, int32(x))
}
func (Response_CodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type CreateVpcGatewayRequest struct {
	Name          string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=Namespace,json=namespace" json:"Namespace,omitempty"`
	GatewayName   string `protobuf:"bytes,3,opt,name=GatewayName,json=gatewayName" json:"GatewayName,omitempty"`
	GatewayHostIP string `protobuf:"bytes,4,opt,name=GatewayHostIP,json=gatewayHostIP" json:"GatewayHostIP,omitempty"`
}

func (m *CreateVpcGatewayRequest) Reset()                    { *m = CreateVpcGatewayRequest{} }
func (m *CreateVpcGatewayRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateVpcGatewayRequest) ProtoMessage()               {}
func (*CreateVpcGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateVpcGatewayRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVpcGatewayRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateVpcGatewayRequest) GetGatewayName() string {
	if m != nil {
		return m.GatewayName
	}
	return ""
}

func (m *CreateVpcGatewayRequest) GetGatewayHostIP() string {
	if m != nil {
		return m.GatewayHostIP
	}
	return ""
}

type CreateSubnetRequest struct {
	Name          string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=Namespace,json=namespace" json:"Namespace,omitempty"`
	Virtual       bool   `protobuf:"varint,3,opt,name=Virtual,json=virtual" json:"Virtual,omitempty"`
	IP            string `protobuf:"bytes,4,opt,name=IP,json=iP" json:"IP,omitempty"`
	Prefix        string `protobuf:"bytes,5,opt,name=Prefix,json=prefix" json:"Prefix,omitempty"`
	Vpc           string `protobuf:"bytes,6,opt,name=Vpc,json=vpc" json:"Vpc,omitempty"`
	Vni           string `protobuf:"bytes,7,opt,name=Vni,json=vni" json:"Vni,omitempty"`
	Status        string `protobuf:"bytes,8,opt,name=Status,json=status" json:"Status,omitempty"`
	RemoteGateway string `protobuf:"bytes,9,opt,name=RemoteGateway,json=remoteGateway" json:"RemoteGateway,omitempty"`
}

func (m *CreateSubnetRequest) Reset()                    { *m = CreateSubnetRequest{} }
func (m *CreateSubnetRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateSubnetRequest) ProtoMessage()               {}
func (*CreateSubnetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateSubnetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSubnetRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateSubnetRequest) GetVirtual() bool {
	if m != nil {
		return m.Virtual
	}
	return false
}

func (m *CreateSubnetRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *CreateSubnetRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *CreateSubnetRequest) GetVpc() string {
	if m != nil {
		return m.Vpc
	}
	return ""
}

func (m *CreateSubnetRequest) GetVni() string {
	if m != nil {
		return m.Vni
	}
	return ""
}

func (m *CreateSubnetRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateSubnetRequest) GetRemoteGateway() string {
	if m != nil {
		return m.RemoteGateway
	}
	return ""
}

type DeleteVpcGatewayRequest struct {
	Name          string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=Namespace,json=namespace" json:"Namespace,omitempty"`
	GatewayName   string `protobuf:"bytes,3,opt,name=GatewayName,json=gatewayName" json:"GatewayName,omitempty"`
	GatewayHostIP string `protobuf:"bytes,4,opt,name=GatewayHostIP,json=gatewayHostIP" json:"GatewayHostIP,omitempty"`
}

func (m *DeleteVpcGatewayRequest) Reset()                    { *m = DeleteVpcGatewayRequest{} }
func (m *DeleteVpcGatewayRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVpcGatewayRequest) ProtoMessage()               {}
func (*DeleteVpcGatewayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteVpcGatewayRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteVpcGatewayRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteVpcGatewayRequest) GetGatewayName() string {
	if m != nil {
		return m.GatewayName
	}
	return ""
}

func (m *DeleteVpcGatewayRequest) GetGatewayHostIP() string {
	if m != nil {
		return m.GatewayHostIP
	}
	return ""
}

type DeleteSubnetRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=Namespace,json=namespace" json:"Namespace,omitempty"`
}

func (m *DeleteSubnetRequest) Reset()                    { *m = DeleteSubnetRequest{} }
func (m *DeleteSubnetRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteSubnetRequest) ProtoMessage()               {}
func (*DeleteSubnetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteSubnetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteSubnetRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type Response struct {
	ReturnCode Response_CodeType `protobuf:"varint,1,opt,name=ReturnCode,json=returnCode,enum=proto.Response_CodeType" json:"ReturnCode,omitempty"`
	Message    string            `protobuf:"bytes,2,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetReturnCode() Response_CodeType {
	if m != nil {
		return m.ReturnCode
	}
	return Response_Error
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*CreateVpcGatewayRequest)(nil), "proto.CreateVpcGatewayRequest")
	proto1.RegisterType((*CreateSubnetRequest)(nil), "proto.CreateSubnetRequest")
	proto1.RegisterType((*DeleteVpcGatewayRequest)(nil), "proto.DeleteVpcGatewayRequest")
	proto1.RegisterType((*DeleteSubnetRequest)(nil), "proto.DeleteSubnetRequest")
	proto1.RegisterType((*Response)(nil), "proto.Response")
	proto1.RegisterEnum("proto.Response_CodeType", Response_CodeType_name, Response_CodeType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MizarService service

type MizarServiceClient interface {
	CreateVpcGateway(ctx context.Context, in *CreateVpcGatewayRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteVpcGateway(ctx context.Context, in *DeleteVpcGatewayRequest, opts ...grpc.CallOption) (*Response, error)
	CreateSubnet(ctx context.Context, in *CreateSubnetRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteSubnet(ctx context.Context, in *DeleteSubnetRequest, opts ...grpc.CallOption) (*Response, error)
}

type mizarServiceClient struct {
	cc *grpc.ClientConn
}

func NewMizarServiceClient(cc *grpc.ClientConn) MizarServiceClient {
	return &mizarServiceClient{cc}
}

func (c *mizarServiceClient) CreateVpcGateway(ctx context.Context, in *CreateVpcGatewayRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.MizarService/CreateVpcGateway", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mizarServiceClient) DeleteVpcGateway(ctx context.Context, in *DeleteVpcGatewayRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.MizarService/DeleteVpcGateway", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mizarServiceClient) CreateSubnet(ctx context.Context, in *CreateSubnetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.MizarService/CreateSubnet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mizarServiceClient) DeleteSubnet(ctx context.Context, in *DeleteSubnetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.MizarService/DeleteSubnet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MizarService service

type MizarServiceServer interface {
	CreateVpcGateway(context.Context, *CreateVpcGatewayRequest) (*Response, error)
	DeleteVpcGateway(context.Context, *DeleteVpcGatewayRequest) (*Response, error)
	CreateSubnet(context.Context, *CreateSubnetRequest) (*Response, error)
	DeleteSubnet(context.Context, *DeleteSubnetRequest) (*Response, error)
}

func RegisterMizarServiceServer(s *grpc.Server, srv MizarServiceServer) {
	s.RegisterService(&_MizarService_serviceDesc, srv)
}

func _MizarService_CreateVpcGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVpcGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MizarServiceServer).CreateVpcGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MizarService/CreateVpcGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MizarServiceServer).CreateVpcGateway(ctx, req.(*CreateVpcGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MizarService_DeleteVpcGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVpcGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MizarServiceServer).DeleteVpcGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MizarService/DeleteVpcGateway",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MizarServiceServer).DeleteVpcGateway(ctx, req.(*DeleteVpcGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MizarService_CreateSubnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MizarServiceServer).CreateSubnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MizarService/CreateSubnet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MizarServiceServer).CreateSubnet(ctx, req.(*CreateSubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MizarService_DeleteSubnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MizarServiceServer).DeleteSubnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MizarService/DeleteSubnet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MizarServiceServer).DeleteSubnet(ctx, req.(*DeleteSubnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MizarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MizarService",
	HandlerType: (*MizarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVpcGateway",
			Handler:    _MizarService_CreateVpcGateway_Handler,
		},
		{
			MethodName: "DeleteVpcGateway",
			Handler:    _MizarService_DeleteVpcGateway_Handler,
		},
		{
			MethodName: "CreateSubnet",
			Handler:    _MizarService_CreateSubnet_Handler,
		},
		{
			MethodName: "DeleteSubnet",
			Handler:    _MizarService_DeleteSubnet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mizar.proto",
}

func init() { proto1.RegisterFile("mizar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0xce, 0xd2, 0x40,
	0x14, 0xb5, 0x05, 0xfa, 0x73, 0xf9, 0x3e, 0x6c, 0x86, 0x44, 0x27, 0x44, 0x0d, 0x69, 0x5c, 0xb8,
	0x62, 0x81, 0x1b, 0x13, 0x97, 0x68, 0xd0, 0x18, 0x94, 0x14, 0xc3, 0x7e, 0xa8, 0x57, 0xd2, 0x84,
	0xb6, 0xe3, 0xcc, 0x14, 0xc5, 0xc4, 0x97, 0xd0, 0xc7, 0xf4, 0x25, 0x4c, 0x67, 0xda, 0x5a, 0xfe,
	0x36, 0xba, 0xf9, 0x56, 0xe4, 0x9e, 0x7b, 0xcf, 0x99, 0x73, 0x39, 0xb7, 0xd0, 0x4f, 0x93, 0xef,
	0x4c, 0x4c, 0xb8, 0xc8, 0x55, 0x4e, 0x7a, 0xfa, 0x27, 0xfc, 0x65, 0xc1, 0xc3, 0x99, 0x40, 0xa6,
	0x70, 0xcd, 0xe3, 0x39, 0x53, 0xf8, 0x95, 0x1d, 0x22, 0xfc, 0x52, 0xa0, 0x54, 0x84, 0x40, 0xf7,
	0x3d, 0x4b, 0x91, 0x5a, 0x63, 0xeb, 0x99, 0x1f, 0x75, 0x33, 0x96, 0x22, 0x79, 0x04, 0x7e, 0x89,
	0x49, 0xce, 0x62, 0xa4, 0xb6, 0x6e, 0xf8, 0x59, 0x0d, 0x90, 0x31, 0xf4, 0x2b, 0x0d, 0x4d, 0xec,
	0xe8, 0x7e, 0x7f, 0xfb, 0x17, 0x22, 0x4f, 0xe1, 0xb6, 0x9a, 0x78, 0x93, 0x4b, 0xf5, 0x76, 0x49,
	0xbb, 0x7a, 0xe6, 0x76, 0xdb, 0x06, 0xc3, 0xdf, 0x16, 0x0c, 0x8d, 0xab, 0x55, 0xb1, 0xc9, 0x50,
	0xfd, 0xbb, 0x23, 0x0a, 0xee, 0x3a, 0x11, 0xaa, 0x60, 0x3b, 0xed, 0xc6, 0x8b, 0xdc, 0xbd, 0x29,
	0xc9, 0x00, 0xec, 0xe6, 0x79, 0x3b, 0x59, 0x92, 0x07, 0xe0, 0x2c, 0x05, 0x7e, 0x4e, 0xbe, 0xd1,
	0x9e, 0xc6, 0x1c, 0xae, 0x2b, 0x12, 0x40, 0x67, 0xcd, 0x63, 0xea, 0x68, 0xb0, 0xb3, 0xe7, 0xb1,
	0x46, 0xb2, 0x84, 0xba, 0x15, 0x92, 0x25, 0x25, 0x77, 0xa5, 0x98, 0x2a, 0x24, 0xf5, 0x0c, 0x57,
	0xea, 0xaa, 0xdc, 0x36, 0xc2, 0x34, 0x57, 0x58, 0xed, 0x4c, 0x7d, 0xb3, 0xad, 0x68, 0x83, 0x3a,
	0x83, 0x57, 0xb8, 0xc3, 0xbb, 0x95, 0xc1, 0x1c, 0x86, 0xc6, 0xd4, 0x7f, 0x46, 0x10, 0xfe, 0x00,
	0x2f, 0x42, 0xc9, 0xf3, 0x4c, 0x22, 0x79, 0x01, 0x10, 0xa1, 0x2a, 0x44, 0x36, 0xcb, 0x3f, 0x19,
	0x8d, 0xc1, 0x94, 0x9a, 0x8b, 0x9c, 0xd4, 0x43, 0x93, 0xb2, 0xf7, 0xf1, 0xc0, 0x31, 0x02, 0xd1,
	0xcc, 0x96, 0x41, 0x2e, 0x50, 0x4a, 0xb6, 0xad, 0x5f, 0x70, 0x53, 0x53, 0x86, 0x8f, 0xc1, 0xab,
	0x19, 0xc4, 0x87, 0xde, 0x6b, 0x21, 0x72, 0x11, 0xdc, 0x23, 0x0e, 0xd8, 0x1f, 0xde, 0x05, 0xd6,
	0xf4, 0xa7, 0x0d, 0x37, 0x8b, 0xf2, 0xf0, 0x57, 0x28, 0xf6, 0x49, 0x8c, 0x64, 0x06, 0xc1, 0xe9,
	0xc5, 0x93, 0x27, 0x95, 0x87, 0x2b, 0x9f, 0xc2, 0xe8, 0xfe, 0x89, 0xc7, 0x52, 0xe4, 0x34, 0xb2,
	0x46, 0xe4, 0x4a, 0x96, 0xe7, 0x22, 0x2f, 0xe1, 0xa6, 0x7d, 0xe5, 0x64, 0x74, 0xe4, 0xe2, 0xe8,
	0x7f, 0xbf, 0x48, 0x6e, 0xe7, 0xd3, 0x90, 0x2f, 0x84, 0x76, 0x46, 0xde, 0x38, 0xba, 0x7e, 0xfe,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x29, 0x10, 0x55, 0x13, 0x04, 0x00, 0x00,
}
