/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/kubeedge/kubeedge/cloud/cmd/inter_cluster_gateway/pkg/apis/divider/client/clientset/versioned/scheme"
	v1 "github.com/kubeedge/kubeedge/cloud/cmd/inter_cluster_gateway/pkg/apis/divider/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DividersGetter has a method to return a DividerInterface.
// A group's client should implement this interface.
type DividersGetter interface {
	Dividers(namespace string) DividerInterface
}

// DividerInterface has methods to work with Divider resources.
type DividerInterface interface {
	Create(ctx context.Context, divider *v1.Divider, opts metav1.CreateOptions) (*v1.Divider, error)
	Update(ctx context.Context, divider *v1.Divider, opts metav1.UpdateOptions) (*v1.Divider, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Divider, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DividerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Divider, err error)
	DividerExpansion
}

// dividers implements DividerInterface
type dividers struct {
	client rest.Interface
	ns     string
}

// newDividers returns a Dividers
func newDividers(c *MizarV1Client, namespace string) *dividers {
	return &dividers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the divider, and returns the corresponding divider object, and an error if there is any.
func (c *dividers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Divider, err error) {
	result = &v1.Divider{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dividers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Dividers that match those selectors.
func (c *dividers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DividerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DividerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dividers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dividers.
func (c *dividers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dividers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a divider and creates it.  Returns the server's representation of the divider, and an error, if there is any.
func (c *dividers) Create(ctx context.Context, divider *v1.Divider, opts metav1.CreateOptions) (result *v1.Divider, err error) {
	result = &v1.Divider{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dividers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(divider).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a divider and updates it. Returns the server's representation of the divider, and an error, if there is any.
func (c *dividers) Update(ctx context.Context, divider *v1.Divider, opts metav1.UpdateOptions) (result *v1.Divider, err error) {
	result = &v1.Divider{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dividers").
		Name(divider.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(divider).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the divider and deletes it. Returns an error if one occurs.
func (c *dividers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dividers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dividers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dividers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched divider.
func (c *dividers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Divider, err error) {
	result = &v1.Divider{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dividers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
